# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMapp', '0002_auto_20170428_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fechaNacimiento', models.DateTimeField()),
                ('tipoSangre', models.TextField()),
            ],
        ),
    ]
