# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMapp', '0004_delete_datosusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fechaNacimiento', models.DateTimeField()),
                ('Tipo_Sangre', models.CharField(choices=[('O+', 'O positivo'), ('O-', 'O negativo'), ('A+', 'A positivo'), ('A-', 'A negativo'), ('B+', 'B positivo'), ('B-', 'B negativo'), ('AB+', 'AB positivo'), ('AB-', 'AB negativo')], max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilMedico',
        ),
    ]
