# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMapp', '0007_auto_20170508_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias_Medicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('alergias', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatosUser1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fechaNacimiento', models.CharField(max_length=50)),
                ('Tipo_Sangre', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=500)),
                ('NotaMedic', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='DatosUser',
        ),
    ]
