# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMapp', '0009_auto_20170529_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=500)),
                ('NotaMedic', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Visitas',
        ),
    ]
