# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMapp', '0010_auto_20170529_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMapp.Pacientes'),
        ),
    ]
